add Sx and N4x / refactor ensenso_description
ensenso/ros_driver pull request #69
Opened 2022-01-27 17:31 UTC by larslevity

2022-01-28 07:53 UTC, saierd requested changes
STL files should be in LFS.

2022-01-28 07:53 UTC, saierd commented on ensenso_description/ensenso.xacro
> +    <joint name="${name}_left_lense_joint" type="fixed">
```suggestion
    <joint name="${name}_left_lens_joint" type="fixed">
```

2022-01-28 07:53 UTC, saierd commented on ensenso_description/ensenso.xacro
> +    <joint name="${name}_left_lense_joint" type="fixed">
```suggestion
    <joint name="${name}_left_lens_joint" type="fixed">
```

2022-01-28 07:53 UTC, saierd commented on ensenso_description/ensenso.xacro
> +    <joint name="${name}_left_lense_joint" type="fixed">
```suggestion
    <joint name="${name}_left_lens_joint" type="fixed">
```

2022-01-28 15:16 UTC, benthie commented
Launch files in ensenso_camera/launch using the xacros need adjustment (xacro name and camera name):
https://github.com/ensenso/ros_driver/blob/master/ensenso_camera/launch/ensenso_N_with_xacro.launch#L20
https://github.com/ensenso/ros_driver/blob/master/ensenso_camera/launch/ensenso_X_with_xacro.launch#L35

2022-01-30 10:38 UTC, larslevity commented
Can you please check if "ensenso_N_with_xacro.launch" works ?

2022-01-31 10:49 UTC, benthie requested changes

2022-01-31 10:49 UTC, benthie commented on ensenso_description/ensenso_N3x_Series.xacro
> +  <link name="$(corresponding_frame_name)" />
Must be {corresponding_frame_name} with curly braces in Line 19, 20 and 25

2022-01-31 10:49 UTC, benthie commented on ensenso_description/ensenso_N3x_Series.xacro
> +<!-- example usage with:
Trailing whitespace

2022-01-31 11:30 UTC, saierd commented
Please make sure that STL files are in LFS from the beginning. When they are part of the Git history everyone has to download all version of them anyway.

2022-01-31 12:15 UTC, benthie requested changes

2022-01-31 12:15 UTC, benthie commented on ensenso_camera/launch/ensenso_N_with_xacro.launch
> +    command="xacro --inorder '$(find ensenso_description)/ensenso_N3x_Series.xacro'
We can drop the `--inorder` argument since in-order processing became default in ROS Melodic.

2022-02-02 14:31 UTC, saierd approved these changes

2022-02-02 14:31 UTC, merged