Add support for S-Series
ensenso/ros_driver pull request #71
Opened 2022-01-28 08:43 UTC by benthie

2022-01-31 07:12 UTC, saierd requested changes

2022-01-31 07:12 UTC, saierd commented on ensenso_camera/nodelets.xml
> +  <class name="ensenso_camera/stereo_camera_nodelet" type="ensenso_camera::StereoCameraNodelet" base_class_type="nodelet::Nodelet">
Ich finde die neuen Namen erstmal gut. Allerdings macht das jetzt natürlich die Launchfiles der Benutzer kaputt. Können wir nicht `nodelet` und `nodelet_mono` ebenfalls noch anbieten?

2022-01-31 07:12 UTC, saierd commented on ensenso_camera/src/camera.cpp
> +    info->binning_x = 0;
1 als Default wäre logischer, auch wenn ROS sagt, dass 0 als 1 interpretiert wird.

2022-01-31 07:12 UTC, saierd commented on ensenso_camera/src/stereo_camera.cpp
> +  updateGlobalLink(imageTimestamp, "", goal->use_cached_transformation);
Das könnten wir uns noch sparen, wenn keine 3D Daten requested wurden.

2022-01-31 07:12 UTC, saierd commented on ensenso_camera/src/stereo_camera.cpp
> +  std::string modelName = cameraNode[itmModelName].asString();
Besser auf Type = StructuredLight checken. ModelName ist evtl. nicht richtig ausgefüllt für virtuelle und Filekameras.

2022-01-31 07:12 UTC, saierd commented
Ich würde mir noch einen Test wünschen, der mal Daten von einer S Filekamera abholt.

2022-02-03 06:47 UTC, saierd requested changes

2022-02-03 06:47 UTC, saierd commented on ensenso_camera/include/ensenso_camera/conversion.h
> +double const NXLIB_TIMESTAMP_OFFSET = 11644473600;
Wird nirgendwo sonst benutzt, oder? Dann sollte das in die cpp Datei.

2022-02-03 06:47 UTC, saierd commented on ensenso_camera/include/ensenso_camera/conversion.h
> +#include "ros/ros.h"
Include sieht unnötig aus. Wenn dann sollte der externe include aber auch in spitze Klammern.

2022-02-03 06:47 UTC, saierd commented on ensenso_camera/include/ensenso_camera/conversion.h
> +#include <cmath>
Wird im Header nicht benutzt, oder?

2022-02-03 06:47 UTC, saierd commented on ensenso_camera/src/camera_nodelet.cpp
> +// #include "ensenso_camera/camera.h"
Weg damit.

2022-02-03 06:56 UTC, saierd commented
Sehr schön. Der S Test muss noch auf SDK >= 3.2 limitiert werden.

Leider gehen auch sonst die Build jetzt regelmäßig nicht mehr? Wegen der fehlgeschlagenen Installation können wir wahrscheinlich wenig machen, oder?

2022-02-03 12:31 UTC, benthie commented
> Sehr schön. Der S Test muss noch auf SDK >= 3.2 limitiert werden.

Die Limitierung für den Tests habe ich eingebaut.

> Leider gehen auch sonst die Build jetzt regelmäßig nicht mehr? Wegen der fehlgeschlagenen Installation können wir wahrscheinlich wenig machen, oder?

Ja, da können wir leider nichts machen. Lokal hat bei mir eben wieder alles einwandfrei funktioniert. Hoffen wir erstmal, dass das nicht regelmäßig zum Problem wird.

2022-02-03 13:30 UTC, saierd approved these changes

2022-02-03 13:30 UTC, merged