Add parameter to open TCP port on NxLib
ensenso/ros_driver pull request #81
Opened 2022-03-24 15:00 UTC by benthie

2022-03-28 07:30 UTC, saierd requested changes

2022-03-28 07:30 UTC, saierd commented on ensenso_camera/src/camera.cpp
> +    ROS_WARN("Link does not exists. Therefore we cannot publish a transform to any target. Error message: %s",
```suggestion
    ROS_WARN("Link does not exist. Therefore we cannot publish a transform to any target. Error message: %s",
```

2022-03-28 07:30 UTC, saierd commented on ensenso_camera/src/camera.cpp
> +  return !isUnitVector(cameraNode[itmLink][itmRotation][itmAxis]);
Das reicht nicht. Könnte ja auch nur eine Translation sein oder eine Rotation um die x Achse.

2022-03-28 07:30 UTC, saierd commented on ensenso_camera/src/stereo_camera.cpp
> +      computePointMap.parameters()["Relative"] = true;
Braucht SDK >= 3.0. Entweder

* wir machen hier einen Check rein, oder
* wir verlangen 3.0, ändern die Doku und zeigen beim Start eine Warnung, falls älter.

2022-03-28 07:30 UTC, saierd commented on ensenso_camera/scripts/request_data
> +    request_data_client_name = rospy.get_param("~namespace", "") + "/request_data"
```suggestion
    request_data_client_name = rospy.get_param("~namespace", "/") + "request_data"
```

Die Idee von den relativen Pfaden ist eigentlich, dass man die im Launchfile in den selben Namespace packen kann oder mit der Umgebungsvariable. Siehe hier: http://wiki.ros.org/Remapping%20Arguments#A.22Pushing_Down.22

Wir können den Parameter auch unterstützen, aber standardmäßig sollte der Pfad überall relativ sein.

2022-04-01 10:11 UTC, saierd commented on ensenso_camera/scripts/request_data
> +    request_data_client_name = rospy.get_param("~namespace", "") + "/request_data"
Ah Moment, mir ist grade aufgefallen, dass meine vorgeschlagene Änderung gar nicht reicht. Das macht den Pfad ja trotzdem absolut, wenn man den Parameter nicht angibt.

2022-04-01 10:23 UTC, saierd requested changes

2022-04-01 10:23 UTC, saierd commented on ensenso_camera/src/pose_utilities.cpp
> +  return (pose.getBasis() == tf2::Matrix3x3::getIdentity());
Das hier reicht immer noch nicht, denn es vergleicht jetzt nur die Rotation. Translation muss auch noch 0 sein.

2022-04-01 10:23 UTC, saierd commented on ensenso_camera/src/pose_utilities.cpp
> +double fixZeroValue(double value, double epsilon = 0.00001)
Ist irgendwie ein bisschen unsympathisch, das immer zu machen. Ich nehme an, das war für den Vergleich mit Identity? In dem Fall sollte die Toleranz beim Vergleichen gehandelt werden, aber eigentlich sollte das an der Stelle keine numerischen Probleme geben.

2022-04-05 06:21 UTC, saierd approved these changes

2022-04-05 06:21 UTC, saierd commented on ensenso_camera/scripts/request_data
> +    request_data_client_name = "request_data" if namespace is None else namespace.strip("/") + "/request_data"
```suggestion
    request_data_client_name = "request_data" if namespace is None else namespace.rstrip("/") + "/request_data"
```

Noch eine Mini-Änderung. Sonst kann man mit dem `namespace` Parameter keinen absoluten Pfad mehr basteln, weil auch links das `/` gestrippt wird. Das wäre evtl. noch eine sinnvolle Anwendung, oder?

2022-04-05 07:05 UTC, benthie commented on ensenso_camera/scripts/request_data
> +    request_data_client_name = "request_data" if namespace is None else namespace.strip("/") + "/request_data"
Macht definitiv Sinn und ist abgeändert.

2022-04-05 07:06 UTC, saierd approved these changes

2022-04-05 13:54 UTC, merged